version: 1
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo

goos: linux
goarch: amd64
binary: figure
dir: .

ldflags:
  - "-X sigs.k8s.io/release-utils/version.gitVersion={{ .Env.VERSION }}"
